spring.application.name=sed

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_USER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
security.jwt.secret=${SECURITY_JWT_SECRET:YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2Rm}
security.jwt.access-token-validity-ms=${SECURITY_JWT_ACCESS_TOKEN_VALIDITY_MS:900000}
security.jwt.refresh-token-validity-ms=${SECURITY_JWT_REFRESH_TOKEN_VALIDITY_MS:604800000}

# Email Configuration (Desarrollo - logs en consola)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false